# Generated by Django 4.1.4 on 2023-01-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Auth',
                'verbose_name_plural': 'Authentications',
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('thumbnail', models.CharField(max_length=255)),
                ('fullframe', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data Request',
            },
        ),
    ]
