# Generated by Django 4.1.4 on 2023-01-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequest',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='facial_creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='matched',
            field=models.BooleanField(default=True),
        ),
    ]
