# Generated by Django 4.1.4 on 2023-01-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facial', '0002_datarequest_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
